<?php include "$_SERVER[DOCUMENT_ROOT]/common/db_conn.php" ?> 
<html>	<head>	<title>主日學預告編輯</title>	  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />	   	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />		<script src="http://code.jquery.com/jquery-1.9.1.js"></script>		<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>	    <script type="text/javascript">	        $(function() {			    $("form :text").width(800);			  });	    </script>	    <style type="text/css">	        div.header {	            font-weight: bolder;	            font-size: 20pt;	        }
	        td.label {	            font-size: 13pt;	            text-align:right;	            width: 20%;	        }
	        td.space {	        	width:5%;	        }	    </style>	</head>	<body>	<?php include $_SERVER[DOCUMENT_ROOT]. '/admin/header.php'; ?>		<div align="center">    <?php    
    $topics_id = $_GET['id'];        $topics_speaker = "";    $topics_title = "";    $topics_verse = "";    $topics_room = "";    $sort_order = "";        if (array_key_exists('save', $_POST)) {    	//Post back        $topics_id = $_POST["topics_id"];        $topics_speaker = $_POST["topics_speaker"];        $topics_title = $_POST["topics_title"];        //$topics_verse = $_POST["topics_verse"];    	//$topics_room = $_POST["topics_room"];    	$sort_order = $_POST["sortOrder"];    	    	if (empty($sort_order)) {    		$sort_order = 1;    	}    	        $db = new PDO('mysql:host='.$db_host.';dbname='.$database,        $username,        $password,        array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));    
        if (empty($topics_id))	{            $db->query("INSERT INTO ch_SundaySchool_News " .    				"	(speaker, title, sort_order) " .    				"	VALUES " .    				"	('$topics_speaker', '$topics_title', '$sort_order')");    
    		echo "创建成功";	    	}    
    	else {    		$db->query("UPDATE ch_SundaySchool_News SET " .    				"	speaker = '$topics_speaker', " .    				"	title ='$topics_title', " .    		        //"	verse ='$topics_verse', " .    				//"	room = '$topics_room', " .    				"	sort_order = '$sort_order'" .    				" WHERE news_id = $topics_id");    		echo "更新成功";    	}    
    	exit();    }    else {                if (!is_null($topics_id)) {    	        		mysql_connect($db_host,$username,$password);    		@mysql_select_db($database) or die( "Unable to select database");    		mysql_query ('SET NAMES utf8');    		$query="SELECT * FROM ch_SundaySchool_News WHERE news_id = $topics_id";    
    		$result=mysql_query($query);    		$num=mysql_numrows($result);    		mysql_close();    		    		  		    		$topics_speaker = mysql_result($result, 0, "speaker");     		$topics_title = mysql_result($result, 0, "title");     		//$topics_verse = mysql_result($result, 0, "verse");     		//$topics_room = mysql_result($result, 0, "room");     		$sort_order = mysql_result($result, 0, "sort_order"); 	    	} ?>
	
	<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="POST">		<table border="0" cellpadding="0" cellspacing="0" width="80%" align="center">			<tr>				<td class="label"></td>				<td class="space"></td>				<td><div class="header"><?php echo is_null($topics_id) ? "创建" : "更新"; ?>主日學預告</div><br></td>			</tr>			<tr>				<td class="label">講員:</td>				<td class="space"></td>				<td><input type="text" name="topics_speaker" id="topics_speaker" value="<?php echo $topics_speaker ?>" /></td>			</tr>			<tr>				<td class="label">題目:</td>				<td class="space"></td>				<td><input type="text" name="topics_title" id="topics_title" value="<?php echo $topics_title ?>" /></td>			</tr>			<!-- 			<tr>				<td class="label">經文:</td>				<td class="space"></td>				<td><input type="text" name="topics_verse" id="topics_verse" value="<?php echo $topics_verse ?>" /></td>			</tr>			<tr>				<td class="label">地點:</td>				<td class="space"></td>				<td><input type="text" name="topics_room" id="topics_room" value="<?php echo $topics_room ?>" /></td>			</tr>			 -->			<tr>				<td class="label">排序</td>				<td class="space"></td>				<td><input type="text" name="sortOrder" id="sortOrder" value="<?php echo $sort_order ?>" /></td>			</tr>			<tr>				<td class="label"></td>				<td class="space"></td>				<td>					<input type="submit" name="save" value="<?php echo is_null($topics_id) ? '创建' : '更新'; ?>" />&nbsp;					<input type="button" name="cancel" value="取消" onclick="javascript:history.back(1);" />				</td>			</tr>		</table>
		<input type="hidden" name="topics_id" value="<?php echo is_null($topics_id) ? '' : $topics_id; ?>" />	</form><?php } ?></div></body></html>